n1 = float(input("Digite Primeiro numero: "))
n2 = float(input("Digite segundo numero"))
n3 = float(input("Digite terceiro numero"))
n4 = float(input("Digite quarto numero"))
n5 = float(input("Digite quinto numero"))
n6 = float(input("Digite sexto numero"))
n7 = float(input("Digite setimo numero"))
n8 = float(input("Digite oitavo numero:"))
n9 = float(input("Digite nono numero:"))
n10 = float(input("Digite Decimo numero:"))
lista = (n1,n2,n3,n4, n5,n6,n7,n8,n9,n10)
print(list(reversed(lista)))
print(lista)
